apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-front
spec:
  selector:
    matchLabels:
      app: web-api-front
  template:
    metadata:
      labels:
        app: web-api-front
    spec:
      containers:
      - name: web-api-front
        image: rcdemoregistry.azurecr.io/rcapps/flask-container-action:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
