apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
spec:
  selector:
    matchLabels:
      app: web-front
  template:
    metadata:
      labels:
        app: web-front
    spec:
      containers:
      - name: web-front
        image: rcregistry.azurecr.io/web-front:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: API_QUOTES
            value: http://api-back:8000
          - name: FLASK_ENV
            value: production