apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-front
  template:
    metadata:
      labels:
        app: web-front
    spec:
      containers:
      - name: web-front
        image: rcregistry.azurecr.io/web-front:4
        imagePullPolicy: Always
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        env:
          - name: API_QUOTES
            value: http://api-back-service:8000
          - name: FLASK_ENV
            value: production